# Generated by Django 2.0.7 on 2021-06-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='utype',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
